apiVersion: apps/v1
kind: Deployment
metadata:
  name: recall-web
  labels:
    app: recall-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recall-web
  template:
    metadata:
      labels:
        app: recall-web
    spec:
      containers:
      - name: recall-web
        image: recall-web:latest
        ports:
        - containerPort: 5000
        env:
        - name: ASSEMBLYAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: recall-secrets
              key: assemblyai-api-key
        - name: FLASK_ENV
          value: "production"
        - name: PYTHONUNBUFFERED
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        volumeMounts:
        - name: transcripts
          mountPath: /app/transcripts
        - name: uploads
          mountPath: /app/uploads
        - name: config
          mountPath: /app/config
        - name: logs
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /api/status
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/status
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
      volumes:
      - name: transcripts
        persistentVolumeClaim:
          claimName: recall-transcripts-pvc
      - name: uploads
        persistentVolumeClaim:
          claimName: recall-uploads-pvc
      - name: config
        configMap:
          name: recall-config
      - name: logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: recall-web-service
spec:
  selector:
    app: recall-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: recall-secrets
type: Opaque
data:
  assemblyai-api-key: # Base64 encoded API key
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recall-config
data:
  # Add any configuration files here
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recall-transcripts-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recall-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recall-ingress
  annotations:
    nginx.ingress.kubernetes.io/client-max-body-size: "500m"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - your-domain.com
    secretName: recall-tls-secret
  rules:
  - host: your-domain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: recall-web-service
            port:
              number: 80 